# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Shaded Futures"

# A description of your site for meta tag, search engine results.
description: '"A society grows great when old men plant trees whose shade they know they shall never sit in. --Greek Proverb"'

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/shaded_futures"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://th3incredibl3hulk.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /shaded_futures/
  - text: About
    url: /shaded_futures/about
  - text: Tags
    url: /shaded_futures/tags
  - text: Quote Generator
    url: /shaded_futures/quote_generator.html


# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#999999'

# Site footer
footer:


# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

#URL Config
#baseurl: "/shaded_futures" # the subpath of your site, e.g. /blog
#url: "https://th3incredibl3hulk.github.io" # the base hostname & protocol for your site, e.g. http://example.com