var quotes=[
    //Inspiring
    '"Know when to be a lion and when to be a fox." --Nicolo Machiavelli',
    '"I stand here not because of the path that lies before me, but becasue of the path that lies behind me." --Morpheus',
    '"Confidence comes from not always being right but from not fearing to be wrong." --Peter T. Mcintyre',
    '"What lies behind us and what lies before us are tiny matters compared to what lies within us." --Ralph Waldo Emerson',
    '"If you wish to know the mind of a man, listen to his words." --Chinese Proverb',
    '"The essence of intelligence is skill in extracting meaning from everyday experience." --Anonymous',
    '"A journey of a thousand miles begins with one step" --Unknown',
    '"Don\'t let the sun set on your anger." --The Bible',
    '"Ours is not to reason why, ours is but to do or die." --Unknown',
    '"Life is not measured by the number of breaths you take, but by the moments that take your breath away." --Unknown',
    '"Pride is a personal attitude which separates excellence from mediocrity." --Unknown',
    '"Some people dream of success...while others wake up and work hard at it." --Unknown',
    '"Don\'t do more than you can do, but don\'t do less either." --Jeff Fletcher',
    '"It\'s so hard when you have to but so easy when you want to." --Unknown',
    '"To be happy at home is the ultimate result of ambition." --Unknown',
    '"A successful man is one who can lay a firm foundation with the bricks others have thrown at him." --Unknown',
    '"What counts is not necessarily the size of the dog in the fight - it\'s the size of the fight in the dog." --Dwight D Eisenhower',
    '"Few are those who see with their own eyes and feel with their own hearts." --Albert Einstein',
    '"It is better to die on your feet than to live on your knees." --Emiliano Zapata',
    '"I must study politics that my sons may have the liberty to study mathematics and philosophy." --John Adams',
    '"Experience is the name everyone gives to their mistakes" --Oscar Wilde',
    '"Every flower must grow through dirt." --Anonymous',
    '"Character may be manifested in the great moments, but it is made in teh small ones" --Phillip Brooks',
    '"You can\'t build a reputation on what you are going to do." --Henry Ford',
    '"He who limps is still walking" --Stainslaw J Lec',
    '"Courage is the price that life exacts for granting peace." --Amelia Earhart',
    '"Do not follow where the path may lead.  Go instead where there is no path and leave a trail" --Unknown',
    '"Be who you are and say what you feel, because those who mind don\'t matter and those who matter don\'t mind" --Dr. Seuss',
    '"The best way to predict the future is to create it." --Unknown',
    '"Of all the things you wear, expression is the most important." --Unknown',
    '"The reward of a thing well done is to have done it." --Ralph Waldo Emerson',
    '"Good manners will open doors that the best education could not." --Clarence Thomas',
    '"Don\'t part with your illusions.  When they are gone, you may still exist but you have ceased to live." --Mark Twain, Following the Equator',
    '"Fall seven, rise eight." --Japanese Proverb',
    '"Do not seek to follow the footsteps of the men of old.  Seek what they sought." --Basho',
    '"Taking steps back can actually end up being steps forward in the direction we want to be going." --Unknown',
    '"Write the bad things that happen to you in the sand, but write the good things that happen to you on a piece of marble." --Arabic Proverb',
    '"Most people never run far enough on their first wind to realize they\'ve got a second" --William James',
    '"Striving for excellence motivates you.  Striving for perfection is demoralizing." --Harriet Braiker',
    '"How body from spirit slowly does unwind'+'\n'+'Until we are pure spirit at the end." --Infirmity by Theodor Roethke',
    '"The devil whispered in my ear \'You\'re not strong enough to withstand the storm.\' Today I whispered in the devil\'s ear \'I am the storm\'" --Unknown',
    '"To laugh often and much, to win the respect of intelligent people and of children, to earn the appreciation of honest critics and endure the betrayal of false friends, to appreciate beauty, to find the best in others, to leave the world a bit better, whether by a healthy child, a garden patch...to know even one life breathed easier because you have lived.  This is to have succeeded!" --Ralph Waldo Emerson',
    '"The World offers you comfort.  But you were not made for comfort.  You were made for greatness." --Pope Benedict XVI',
    '"We must all suffer from one of two pains: the pain of discipline or the pain of regret." --Jim Rohn',
    '"Great empires are not maintained by timidity." --Tacitus',
    '"There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self." --Unknown',
    '"I don\'t count my sit ups; I only start counting when it starts hurting because they\'re the only ones that count." --Muhammad Ali',
    '"Replace \'I don\'t have time\' with \'It\'s not important\' and see how that feels." --Robin Arzon',
    '"Reasons to live give reasons to die" --Mav, The Hate U Give',
    '"In order to mold his people, God often has to melt them." --Amish Proverb',
    '"Don\'t ever become a pessimist...a pessimist is correct oftener than an optimist, but an optimist has more fun, and neither can stop the march of events." --Robert A. Heinlen',
    '"You can\'t go back and change the beginning, but you can start where you are and change the ending." --C.S. Lewis',
    '"The Chinese use two brush strokes to write the word \'crisis\'. One brush stroke for danger; the other for opportunity. In a crisis, be aware of the danger but recognize the opportunity" --John F. Kennedy',
    '"We are kept keen on the grindstone of pain and necessity." -- H.G. Wells, The Time Machine',
    '"Whatever nightmares the future holds are dreams compared to what\'s behind me." --Gamora, Guardians of the Galaxy',
    '"Some people can read \'War and Peace\' and come away thinking it\'s a simple adventure story.  Others can read the ingredients on a chewing gum wrapper and unlock the secrets of the universe." --Lex Luthor, Superman',
    '"Once you\'ve accepted your flaws, no one can use them against you." --Peter Dinklage',
    '"Teach your children early what you learned late." --Richard Feynman',
    '"One day or dat one.  You decide." --Unknown',
    '"The last mile is always the least crowded." --Unknown',
    '"He who conquers others is strong; he who conquers himself is mighty." --Lao Tzu, Tao Te Ching',
    '"The bravest are surely those who have the clearest vision of what is before them, glory and danger alike, and yet not withstanding, go out to meet it." --Thucydides',
    '"Be ashamed to die until you have won some victory for humanity." --Horace Mann',
    '"Success is stumbling from failure to failure with no loss of enthusiasm." --Winston Churchill',

    //Miscellaneous
    '"What is presented without evidence can be refuted without evidence" --Christopher hitchens',
    '"Weakness and ignorance are not barriers to survival, but arrogance is" --Cixin Liu, Death\'s End',
    '"Don\’t cling to a mistake just because you spent a lot of time making it" --Unknown',
    '"If you find yourself in a fair fight your tactics suck" --Unknown',
    '"Truth is like poetry. And most people fucking hate poetry" --Overheard in a DC bar',
    '"The Nation that makes a great distinction between its scholars and its warriors will have its thinking done by cowards and its fighting done by fools. --Thucydides"'        
]

function newQuote(){
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber]
}