var quotes=[
    //Inspiring
    '"Know when to be a lion and when to be a fox." --Nicolo Machiavelli',
    '"I stand here not because of the path that lies before me, but becasue of the path that lies behind me." --Morpheus',
    '"Confidence comes from not always being right but from not fearing to be wrong." --Peter T. Mcintyre',
    '"What lies behind us and what lies before us are tiny matters compared to what lies within us." --Ralph Waldo Emerson',
    '"If you wish to know the mind of a man, listen to his words." --Chinese Proverb',
    '"The essence of intelligence is skill in extracting meaning from everyday experience." --Anonymous',
    '"A journey of a thousand miles begins with one step" --Unknown',
    '"Don\'t let the sun set on your anger." --Ephesians 4:26',
    '"Ours is not to reason why, ours is but to do or die." --Unknown',
    '"Life is not measured by the number of breaths you take, but by the moments that take your breath away." --Unknown',
    '"Pride is a personal attitude which separates excellence from mediocrity." --Unknown',
    '"Some people dream of success...while others wake up and work hard at it." --Unknown',
    '"Don\'t do more than you can do, but don\'t do less either." --Jeff Fletcher',
    '"It\'s so hard when you have to but so easy when you want to." --Unknown',
    '"To be happy at home is the ultimate result of ambition." --Unknown',
    '"A successful man is one who can lay a firm foundation with the bricks others have thrown at him." --Unknown',
    '"What counts is not necessarily the size of the dog in the fight - it\'s the size of the fight in the dog." --Dwight D Eisenhower',
    '"Few are those who see with their own eyes and feel with their own hearts." --Albert Einstein',
    '"It is better to die on your feet than to live on your knees." --Emiliano Zapata',
    '"I must study politics that my sons may have the liberty to study mathematics and philosophy." --John Adams',
    '"Experience is the name everyone gives to their mistakes" --Oscar Wilde',
    '"Every flower must grow through dirt." --Anonymous',
    '"Character may be manifested in the great moments, but it is made in teh small ones" --Phillip Brooks',
    '"You can\'t build a reputation on what you are going to do." --Henry Ford',
    '"He who limps is still walking" --Stainslaw J Lec',
    '"Courage is the price that life exacts for granting peace." --Amelia Earhart',
    '"Do not follow where the path may lead.  Go instead where there is no path and leave a trail" --Unknown',
    '"Be who you are and say what you feel, because those who mind don\'t matter and those who matter don\'t mind" --Dr. Seuss',
    '"The best way to predict the future is to create it." --Unknown',
    '"Of all the things you wear, expression is the most important." --Unknown',
    '"The reward of a thing well done is to have done it." --Ralph Waldo Emerson',
    '"Good manners will open doors that the best education could not." --Clarence Thomas',
    '"Don\'t part with your illusions.  When they are gone, you may still exist but you have ceased to live." --Mark Twain, Following the Equator',
    '"Fall seven, rise eight." --Japanese Proverb',
    '"Do not seek to follow the footsteps of the men of old.  Seek what they sought." --Basho',
    '"Taking steps back can actually end up being steps forward in the direction we want to be going." --Unknown',
    '"Write the bad things that happen to you in the sand, but write the good things that happen to you on a piece of marble." --Arabic Proverb',
    '"Most people never run far enough on their first wind to realize they\'ve got a second" --William James',
    '"Striving for excellence motivates you.  Striving for perfection is demoralizing." --Harriet Braiker',
    '"How body from spirit slowly does unwind'+'\n'+'Until we are pure spirit at the end." --Infirmity by Theodor Roethke',
    '"The devil whispered in my ear \'You\'re not strong enough to withstand the storm.\' Today I whispered in the devil\'s ear \'I am the storm\'" --Unknown',
    '"To laugh often and much, to win the respect of intelligent people and of children, to earn the appreciation of honest critics and endure the betrayal of false friends, to appreciate beauty, to find the best in others, to leave the world a bit better, whether by a healthy child, a garden patch...to know even one life breathed easier because you have lived.  This is to have succeeded!" --Ralph Waldo Emerson',
    '"The World offers you comfort.  But you were not made for comfort.  You were made for greatness." --Pope Benedict XVI',
    '"We must all suffer from one of two pains: the pain of discipline or the pain of regret." --Jim Rohn',
    '"Great empires are not maintained by timidity." --Tacitus',
    '"There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self." --Unknown',
    '"I don\'t count my sit ups; I only start counting when it starts hurting because they\'re the only ones that count." --Muhammad Ali',
    '"Replace \'I don\'t have time\' with \'It\'s not important\' and see how that feels." --Robin Arzon',
    '"Reasons to live give reasons to die" --Mav, The Hate U Give',
    '"In order to mold his people, God often has to melt them." --Amish Proverb',
    '"Don\'t ever become a pessimist...a pessimist is correct oftener than an optimist, but an optimist has more fun, and neither can stop the march of events." --Robert A. Heinlen',
    '"You can\'t go back and change the beginning, but you can start where you are and change the ending." --C.S. Lewis',
    '"The Chinese use two brush strokes to write the word \'crisis\'. One brush stroke for danger; the other for opportunity. In a crisis, be aware of the danger but recognize the opportunity" --John F. Kennedy',
    '"We are kept keen on the grindstone of pain and necessity." -- H.G. Wells, The Time Machine',
    '"Whatever nightmares the future holds are dreams compared to what\'s behind me." --Gamora, Guardians of the Galaxy',
    '"Some people can read \'War and Peace\' and come away thinking it\'s a simple adventure story.  Others can read the ingredients on a chewing gum wrapper and unlock the secrets of the universe." --Lex Luthor, Superman',
    '"Once you\'ve accepted your flaws, no one can use them against you." --Peter Dinklage',
    '"Teach your children early what you learned late." --Richard Feynman',
    '"One day or dat one.  You decide." --Unknown',
    '"The last mile is always the least crowded." --Unknown',
    '"He who conquers others is strong; he who conquers himself is mighty." --Lao Tzu, Tao Te Ching',
    '"The bravest are surely those who have the clearest vision of what is before them, glory and danger alike, and yet not withstanding, go out to meet it." --Thucydides',
    '"Be ashamed to die until you have won some victory for humanity." --Horace Mann',
    '"Success is stumbling from failure to failure with no loss of enthusiasm." --Winston Churchill',
    '"He who opens a school door, closes a prison." --Victor Hugo',
    '"In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing." --Theodore Roosevelt',
    //Inspiring
    '"I never lose.  I either win or learn." --Nelson Mandela',
    '"Well done is better than well said." --Benjamin Franklin',
    '"Be a warrior, not a worrier." --Unknown',
    '"Don\'t cling to a mistake just because you spent a lot of time making it." --Unknown',
    '"Be the kind of man that when your feet hit the floor in the morning, the devil says \'Oh shit, he\'s up!\'"',
    '“I never, in my life, felt more certain that I was doing right, than I do in signing this paper. If my name ever goes into history it will be for this act, and my whole soul is in it.” — Abraham Lincoln, signing the Emancipation Proclamation',
    '"If we don\'t change direction soon, we\'ll end up where were going." --Irwin Corey',
    '"Those who do not move, do not notice their chains." --Rosa Luxemburg',
    '"What I cannot create, I do not understand." -- Richard Feynman',
    '"Marines never die, they just go to hell and regroup." -- Unkown',
    '"I am only one, but still I am one. I cannot do everything, but still I can do something; and because I cannot do everything, I will not refuse to do something that I can do." -- Edward Everett Hale',
    '"During a gold rush, sell shovels." -- Saying from the California gold rush, mid-19th century',
    '"Be greedy when others are fearful, be fearful when others are greedy" -- Warren Buffet',
    '"Ours is essentially a tragic age, so we refuse to take it tragically." -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"Then tell Wind and Fire where to stop,” returned madame; “but don\'t tell me." -- Charles Dickens, A Tale of Two Cities',
    '"Fools talk, cowards are silent, wise men listen." -- Carlos Ruiz Zafon, The Shadow of the Wind',
    '"We\'ll start the war from right here!” -- Theodore Roosevelt, Jr when he was delivered to the wrong beach on D-Day',
    '"You\'re born looking like your dad but you die looking like your decisions." -- Unknown',
    '"I am only one, but still I am one. I cannot do everything, but still I can do something; and because I cannot do everything, I will not refuse to do something that I can do.” -- Edward Everett Hale',
    '"Envy is the art of counting someone else\'s blessings instead of your own." -- Harold Coffin',
    '"Don\'t let your ice cream melt while you\'re counting someone else\'s sprinkles." -- Akilah Hughes',
    '"Clifford and his cronies were not anti-social; they were more or less bent on saving mankind, or on instructing it, to say the least." -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"Do not be sorry. Be better." -- Kratos, God of War',

    //Kindness & Compassion
    '"\'I\'m sorry\' is like a band-aid for hurt feelings." --Unknown', //Larry Hau
    '"To err is human, to forgive is divine." --William Shakespeare',
    '"I don\'t like that man very much.  I must get to know him better." --Abraham Lincoln',
    '"Of all the preposterous assumptions of humanity over humanity, nothing exceeds most of the criticisms made on the habits of the poor by the well-housed, well-warmed, and well-fed." --Herman Melville',
    '"Be kind for everyone you meet is fighting a battle you know nothing about."  --Plato',
    '"If men could only know each other, they would neither idolize nor hate." --Elbert Hubbard',

    //Love 
    '"At the touch of love, everyone becomes a poet." --Plato',
    '"You are loved but more importantly, you are worthy of love." --Mena, The Paradox Hotel',
    '"There\'s so much of you here with me, really, that it\'s a pity you aren\'t all here.” -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"There\'s lots of good fish in the sea...maybe...but the vast masses seem to be mackerel or herring, and if you\'re not mackerel or herring yourself, you are likely to find very few good fish in the sea.” -― D.H. Lawrence, Lady Chatterley\'s Lover',

    //Miscellaneous
    '"Don\'t lose your temper, some poor soul may find it." --Unknown',
    '"A series of unfortunate events may be the first steps of a journey." --Lemony Snicket, Lemony Snicket\'s: A Series of Unfortunate Events',
    '"Egotism is the anesthetic that dulls the pain of stupidity" --Frank Leahy',
    '"Walk softly and carry a big stick." --Theodore Roosevelt',
    '"Discussion is an exchange of knowledge, argument is an exchange of ignorance" --Unknown',
    '"God is like an imaginary friend for adults" --Unknown',
    '"Art washes away from the soul, the dust of everyday life." --Pablo Picasso',
    '"When we all think alike, no one thinks much." --Unknown',
    '"Victory has a hundred fathers, defeat is an orphan." --John F. Kennedy',
    '"I\'m always fascinated by the way memory diffuses fact." --Diane Sawyer',
    '"Prediction is very difficult, especially about the future." --Neils Bohr',
    '"It infuriates me to be wrong when I know I\'m right." --Moliere',
    '"Time and distance are obstructions that divide us only when our minds allow them to." --Unknown', //Larry Hau
    '"For there is nothing either good or bad but thinking makes it so." --William Shakespeare, Hamlet',
    '"A real friend is one who walks in when the rest of the world walks out." --Walter Winchell',
    '"Power corrupts but absolute power corrupts absolutely" --Lord Acton',
    '"A single death is a tragedy; a million deaths is a statistic" --Josef Stalin',
    '"A society of sheep must in time beget a government of wolves" --Bertrand de Jouvenel',
    '"The man who strikes first admits that his ideas have given out." --Chinese Proverb',
    '"A people that values its privileges above its principles soon loses both." --Dwight D. Eisenhower',
    '"The death of democracy is not likely to be an assassination from ambush.  It will be a slow extinction from apathy, indifference, and undernourishment." --Robert Hutchins',
    '"All that is necessary for the triumph of evil is that good men do nothing." --Edmund Burke',
    '"I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones." --Albert Einstein',
    '"\'Silent\' and \'Listen\' are spelled with the same letters." --Unknown',
    '"If you think education is expensive, try ignorance." --Derek Bok',
    '"We fear things in proportion to our ignorance of them." --Titus Livius',
    '"A picture is a poem without words." --Horace',
    '"Self-discipline is when your conscience tells you to do something and you don\'t talk back." --W.K. Hope',
    '"Rudeness is the weak man\'s imitation of strength." --Eric Hoffer',
    '"If gold rust, what then will iron do?" --Chaucer, Canterbury Tales',
    '"Brevity is the soul of wit." --William Shakespeare, Hamlet',
    '"I was sorry to have my name mentioned as one of the great authors because they have a sad habit of dying off.  Chaucer is dead, Spencer is dead, so is Milton, so is Shakespeare, and I\'m not feeling so well myself." --Mark Twain, The History of the Savage Club (speech)',
    '"The only reason god created man is because he was disappointed with the monkey" --Mark Twain, autobiographical dictation',
    '"\'Classic\', a book people praise and don\'t read." --Mark Twain, Following the Equator',
    '"There are many humorous things in the world; among them, the white man\'s notion that he is less savage than other savages." --Mark Twain, Following the Equator',
    '"Wrinkles should merely indicate where smiles have been." --Mark Twain, Following the Equator',
    //Miscellaneous
    '"France has neither winter nor summer nor morals.  Apart from these drawbacks, it is a fine country." --Mark Twain',
    '"The radical invents the views.  When he has worn them out, the conservative adopts them." --Mark Twain',
    '"Never let your schooling interfere with your education." --Mark Twain',
    '"Suppose you were an idiot.  And suppose you were a member of congress.  But I repeat myself." --Mark Twain',
    '"America is built on a tilt and everything loose slides to California." --Mark Twain',
    '"Clothes make the man.  Naked people have little or no influence on society." --Mark Twain',
    '"When I was a boy of fourteen, my father was so ignorant I could hardly stand to have the old man around.  But when I got to be twenty-one, I was astonished at how much the old man had learned in seven years." --Mark Twain',
    '"Never lie, steal, cheat, or drink.  But if you must lie, lie in the arms of the one you love.  If you must steal, steal away from bad company.  If you must cheat, cheat death.  And if you must drink, drink in the moments that take your breath away." --Will Smith, Hitch',
    '"Always remember that you are absolutely unique.  Just like everyone else." --Margaret Mead',
    '"Nothing is easier than self-deceit.  For what each man wishes, that he also believes to be true" --Demosthenes',
    '"The road to a friend\'s house is never long" --Danish Proverb',
    '"A true friend is one soul divided into two people" --Aristotle',
    '"I value the friend who, for me, finds time on his calendar but I cherish the friend who, for me, does not consult his calendar." --Robert Brault',
    '"It is amazing how humanity can degrade a situation into total violence and chaos and, upon the appearance of a leader and movement, marvel at its own ability to fix it." --Unknown', //Larry Hau
    '"Forgive me, my friends, for the length of my speech.  If I\'d had more time to write it, it would have been shorter." --Abraham Lincoln',
    '"Be sure you put your feet in the right place and then stand firm." --Abraham Lincoln',
    '"You\'re never as good as everyone tells you when you win and you\'re never as bad as they say when you love." --Lou Holtz',
    '"For disappearing acts, it\'s hard to beat what happens to the eight hours supposedly left after eight of sleep and eight of work." --Doug Lasson',
    '"I want it said of me by those who knew me best, that I always plucked a thistle and planted a flower where I thought a flower would grow." --Abraham Lincoln',
    '"It takes less time to do a thing right than to explain why you did it wrong." --Henry Wadsworth Longfellow',
    '"Trust, like the soul, never returns once it goes." --Latin Proverb',
    '"We are born charming, fresh, and spontaneous and must be civilized before we are fit to participate in society." --Judith Martin',
    '"Why, when I can come back with about two million of my countrymen." --Edgar Ansel Mowrer, journalist exiled from Germany, answering taunt from Nazi official on when he would return',
    '"The worst part of getting old is other men stop seeing you as dangerous." --Act of Valor',
    '"To learn who rules over you, simply find out who you are not allowed to criticize." --Voltaire',
    '"It is not the critic who counts; not the man who points out how the strong man stumbles or where the doer of deeds could have done them better.  The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement and who at worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who know neither victory nor defeat." --Theodore Roosevelt, The Man in the Arena',
    '"The secret source of humor is not joy but sorrow; there is no humor in heaven." --Mark Twain',
    '"Everyone is a moon, and has a dark side which he never shows to anybody." --Mark Twain',
    '"If a leader does not know his destination, any path will take him there." --Lewis Carroll',
    '"The art of prophecy is very difficult - Especially with respect to the future." --Mark Twain',
    '"Idle hands do the devil\'s work." --Professor Powell, Indiana University',
    '"Cut your chains and you become free.  Cut your roots and you die.  Differentiating between the two, however, requires the judgment of experience." --Unknown',
    '"Have no fear of perfection. You\'ll never reach it. --Salvador Dali',
    '"A tiger cannot change its strips." --Tom Hanks, Cloud Atlas',
    '"The weak are meat and the strong do eat." --Tom Hanks, Cloud Atlas',
    '"Something lurks in that soup. We would do well not to thrust into it too deeply." --German Admiral Hipper, Battle of Jutland, WWI',
    '"A fanatic is one who can\'t change his mind and won\'t change the subject." --Winston Churchill',
    '"There are decades where nothing happens; and there are weeks where decades happen." --Vladimir Lenin',
    '"Not all who wander are lost." --JRR Tolkien',
    '"Fear an old man in a profession where men die young." --Unknown',
    '"However beautiful the strategy, you shoudl occassionally look at the results." --Unknown',
    '"We hire for skills and the whole person shows up." --Unknown',
    '"If you want to go fast, go alone.  If you want to go far, go together." --African Proverb',
    '"Give every man thine ear, but few thy voice; take each man\'s censure but reserve thy judgment." --Unknown',
    '"The noblest art is that of making others happy." --PT Barnum',
    '"An empire toppled by its enemies can rise again but one which crumbles from within, is dead forever" --Zemo, Captain America: Civil War',
    '"Make no little plans; they have no magic to stir men\'s blood." --Daniel H Burnam, Director of Works, Worlds Columbian Exposition, 1893',
    '"Children have never been very good at listening to their elders but they have never failed to imitate them." --James Baldwin',
    '"The essence of war is violence and moderation in war is imbecility." --British Admiral Jacky Fisher',
    '"If the ignorant want to believe, they\'ll find a way." --Utopia (movie)',
    '"They\'ve got us surrounded again, the poor bastards." --General Creighton Williams Abrams Jr',
    '"Whether it is to be utopia or oblivion will be a touch and go relay race right up until the final moment." --Buckminster Fuller, futurist',
    '"Every word is like an unnecessary stain on silence and nothingness." --Samuel Beckett',
    '"The battlefield is a scene of constant chaos. The winner will be the one who controls that chaos, both his and the enemies." --Napoleon Bonaparte',
    '"If you are not prepared to use force to defend civilization then be prepared to accept barbarism." --Thomas Sowell',
    '"There is only one principle of war.  Hit the other fellow, as quickly as you can, as hard as you can, where it hurts him most..." --William Slim',
    '"The inherent view of capitalism is the unequal sharing of blessings; the inherent view of socialism is the equal sharing of miseries." --Winston Churchill',
    '"Without a sign, his sword the brave man draws, and asks no omen, but his country\'s cause" --Homer, The Iliad',
    '"Those that sow the wind will reap the whirlwind." --Hosea 8:7',
    '"History is filled with the sound of silken slippers going downstairs and wooden shoes coming up." --Voltaire discussing civilization decline',
    '"Beware that, when fighting monsters, you yourself do not become a monster...for when you gaze long into the abyss, the abyss gazes also into you." --Friederich Nietzsche',
    '"If you want to play god, you have to be acquainted with the devil." --Robert Ford, Westworld',
    '"There are two times in a man\'s life when he should not speculate: when he can\'t afford it and when he can." --Mark Twain',
    '"It spoils the bow to always keep it straight." --Unknown',
    '"Violence.  The supreme authority from which all other authorities are derived." --Nairobi Kenya',
    '"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." --Stephen Hawking',
    '"He who knows only his own side of the case, knows little of that." --John Stuart Mill',
    '"Behind every great leader there was an even greater logistician." --M. Cox',
    '"The line between disorder and order lies in logistics." Sun Tzu',
    '"Amateurs talk about tactics, but professionals study logistics." --General Robert H Barrow, Commandant USMC',
    '"Give me a one-handed economist.  All my economists say \'on the one hand....\' then\'but on the other hand\'" --Harry Truman',
    '"Art should comfort the disturbed and disturb the comforted." --Banksy',
    '"Only when the tide goes out do you discover who\'s been swimming naked." --Warren Buffet',
    '"Any man whose errors take ten years to correct is quite a man." --Robert Oppenheimer',
    '"If you win, say nothing. If you lose, say less." --Paul Brown',
    '"He who angers you, conquers you." --Elizabeth Kenny',
    '"Courage is fire and bullying is smoke." --Benjamin Disraeli',
    '"What is presented without evidence can be refuted without evidence." --Christopher Hitchens',
    '"We thus conclude that the conduct of war is fundamentally a dynamic process of human competition, requiring both the knowledge of science and the creativity of art, but driven ultimately by the power of human will." --USMC, MCDP1 Warfighting',
    '"Truth is like poetry. And most people fucking hate poetry." --Overheard in a DC bar',
    '"Hey, did you hear the Italians made a new fleet of Navy ships? They made them with glass bottoms so that you can see the old ships from last year" --WWII joke',
    //Miscellaneous
    '"Once we are done with Italy, people won\'t travel as far as Naples to see the Italian ruins." --Winston Churchill',
    '"If you find yourself in a fair fight your tactics suck." --Unknown',
    '"I am a patient man and I have much to do." --Odd Thomas',
    '"Weakness and ignorance are not barriers to survival, but arrogance is." -- Cixin Liu, Death\'s End',
    '"The Nation that makes a great distinction between its scholars and its warriors will have its thinking done by cowards and its fighting done by fools. --Thucydides"',
    '"There is no frigate like a book to take us lands away" --Emily Dickinson',
    '"When you leave it to chance then you all of a sudden don’t have anymore luck"  --Unknown',
    '"You ain’t the boss of me sir you surely ain’t. The only thing you could do right now is kill me and you still wouldn\'t be the boss of me" --The Long Earth by Terry Pratchett',
    '"There is no shortcut to any place worth going." --Beverly Sills',
    '"I am very poorly today and very stupid and hate everybody and everything." --Charles Darwin, Letter to Charles Lyell, Oct 1 1861',
    '"Everything is vague to a degree you do not realize until you try to make it precise."  -- Bertrand Russell',
    '"Don\'t estimate all of humanity by the limits of your own capability." --Unknown',
    '""A man with one watch always knows the time but a man with two watches is never sure." -- Unknown',
    '"The horrors persist but so do I" -- Internet Meme',
    '"She wished some help would come from outside. But in the whole world there was no help. Society was terrible because it was insane. Civilized society is insane. Money and so-called love are its two great manias; money a long way first. The individual asserts himself in his disconnected insanity in these two modes: money and love." -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"No, it\'s man that poisons the universe” -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"If you could only tell them that living and spending isn\'t the same thing!" -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"Money poisons you when you\'ve got it, and starves you when you have\'t." -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"The men are limp, they feel a doom somewhere, and they go about as if there was nothing to be done.  Anyhow, nobody knows what should be done in spite of all the talk, the young ones get mad because they\'ve no money to spend.  Their whole life depends on spending money, and now they\'ve got none to spend.  That\'s our whole civilization and our education: bring up the masses to depend entirely on spending money, and then the money gives out." -- D.H. Lawrence, Lady Chatterly\'s Lover',
    '"Friendship means little when it\'s convenient" -- Koji Shimazu',
    '"Before we had billionaire CEOs there was money in this country" -- Some random grandma mentioned in a Reddit post',
    '"The only thing new in the world is the history you do not know." ―- Harry S. Truman',
    '"John Bull can stand many things, but he can\’t stand 2 percent" -- Walter Bagehot \n \n Penned in 1852 in regards to investor demand for yields higher than 2%, even when risking speculation.  \"John Bull\" was just a generic name for an investor in England at that time.',
    '"So, just to be clear, the choices here are \'homicidal maniac\' or \'shit tornado\'?" -- John Scalzi, Kaiju Preservation Society',
    '"Power is the ultimate aphrodisiac" -— Henry Kissinger',
    '"In a guerrilla war, the guerrilla wins if he does not lose. The conventional army loses if it does not win.” -— Henry Kissinger',

    //Religion
    '"If there is no God, than I am God." --Fyodor Dostoevsky',
    '"What the mind of man can conceive and believe, it can achieve." --Napoleon Hill',
    '"God\'s inhumanity to man makes countless thousands mourn." --Mark Twain',
    '"But the truth is, that when a library expels a book of mine and leaves an unexpurgated bible lying around where unprotected youth and age can get hold of it, the deep unconscious irony of it delights me and doesn\'t anger me." --Mark Twain',
    '"I have found solace in profanity unexcelled even by prayer." --Mark Twain',
    '"And shepherds we shall be, for thee my lord for thee.  Power hath descended forth from thy hand, that our feet may swiftly carry out they command.  So we shall flow a river forth to thee, and teeming with souls shall it ever be.  In nomine Patris, et Filii, et Spiritus Sancti." --Il Duce, Connor and Murphy McManus, Boondock Saints',
    '"The government of the United States is not, in any sense, founded on the Christian religion." --Treaty of Tripoli, by John Adams',
    '"God is either cruel or incompetent." --Unknown',
    '"To know a person\'s religion we need not listen to his profession of faith but must find his brand of intolerance." --Eric Hoffer',
    '"Anyone who can worship a trinity and insist that his religion is a monotheism can believe anything, just give him time to rationalize it." --Robert Heinlein',
    '"Government oppressed the body of the wage-slave, but religion oppressed his mind and poisoned the stream of progress at its source." --Upton Sinclair',
    '"If God did not exist, it would be necessary to invent him." --Voltaire',
    '"Where the Romans create a wasteland, they call it peace." --Tacitus',
    '"The more corrupt the government, the more numerous the laws." --Tacitus',
    '"Operationally, God is beginning to resemble not a ruler, but the last fading smile of a cosmic Cheshire cat." --Julian Huxley',
    '"Death, so called, is a thing which makes men weep, and yet a third of life is spent in sleep." --Lord Byron',
    '"You know why god could create the universe in six days?  He didn\'t have an install base." --Subroto Mukerji',
    '"In the beginners mind there are many possibilities , in the experts mind there are few." --Zen Master Shunryu Suzuki',
    '“Capitalism without failure is like religion without hell” Berkshire Hathaway Inc. Vice Chairman Charlie Munger has said, paraphrasing the late economist Allan Meltzer.',
    '"Before we\'re through with them, the Japanese language will be spoken only in hell." --Admiral William Halsey Jr',
    '"The wicked flee when no man pursueth: but the righteous are bold as a lion." -- Proverbs 28:1',
    '"Nothing had been so hateful in the sight of these mobs as the man of learning, at first because they had served the princes, but then later because they refused to join in the bloodletting and tried to oppose the mobs, calling the crowds \'bloodthirsty simpletons.\' \n Joyfully the mobs accepted the name, took up the cry: Simpletons! Yes, yes! I\'m a simpleton! Are you a simpleton? We\'ll build a town and we\'ll call it Simple Town, because by then all the smart bastards that caused all this, they\'ll be dead! SImpletons! Let\'s go! This ought to show \'em! Anybody here not a simpleton? Get the bastard, if there is!" -- Walter Miller, A Canticle for Leibowitz, 1959'
]

function newQuote(){
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber]
}